#pragma once


struct shared
{
    FARPROC DllCanUnloadNow;
    FARPROC DllGetClassObject;
    FARPROC DllRegisterServer;
    FARPROC DllUnregisterServer;
    FARPROC DebugSetMute;

    void LoadOriginalLibrary(HMODULE dll)
    {
        DllCanUnloadNow = GetProcAddress(dll, "DllCanUnloadNow");
        DllGetClassObject = GetProcAddress(dll, "DllGetClassObject");
        DllRegisterServer = GetProcAddress(dll, "DllRegisterServer");
        DllUnregisterServer = GetProcAddress(dll, "DllUnregisterServer");
        DebugSetMute = GetProcAddress(dll, "DebugSetMute");
    }
} shared;



struct binkw32_dll
{
    HMODULE dll;
    FARPROC BinkAllocateFrameBuffers;
    FARPROC BinkBufferBlit;
    FARPROC BinkBufferCheckWinPos;
    FARPROC BinkBufferClear;
    FARPROC BinkBufferClose;
    FARPROC BinkBufferGetDescription;
    FARPROC BinkBufferGetError;
    FARPROC BinkBufferLock;
    FARPROC BinkBufferOpen;
    FARPROC BinkBufferSetDirectDraw;
    FARPROC BinkBufferSetHWND;
    FARPROC BinkBufferSetOffset;
    FARPROC BinkBufferSetResolution;
    FARPROC BinkBufferSetScale;
    FARPROC BinkBufferUnlock;
    FARPROC BinkCheckCursor;
    FARPROC BinkClose;
    FARPROC BinkCloseTrack;
    FARPROC BinkControlBackgroundIO;
    FARPROC BinkControlPlatformFeatures;
    FARPROC BinkCopyToBuffer;
    FARPROC BinkCopyToBufferRect;
    FARPROC BinkCurrentSubtitle;
    FARPROC BinkDDSurfaceType;
    FARPROC BinkDX8SurfaceType;
    FARPROC BinkDX9SurfaceType;
    FARPROC BinkDoFrame;
    FARPROC BinkDoFrameAsync;
    FARPROC BinkDoFrameAsyncMulti;
    FARPROC BinkDoFrameAsyncWait;
    FARPROC BinkDoFramePlane;
    FARPROC BinkFindXAudio2WinDevice;
    FARPROC BinkFreeGlobals;
    FARPROC BinkGetError;
    FARPROC BinkGetFrameBuffersInfo;
    FARPROC BinkGetGPUDataBuffersInfo;
    FARPROC BinkGetKeyFrame;
    FARPROC BinkGetPalette;
    FARPROC BinkGetPlatformInfo;
    FARPROC BinkGetRealtime;
    FARPROC BinkGetRects;
    FARPROC BinkGetRects4;
    FARPROC BinkGetSubtitleByIndex;
    FARPROC BinkGetSummary;
    FARPROC BinkGetTrackData;
    FARPROC BinkGetTrackData12;
    FARPROC BinkGetTrackID;
    FARPROC BinkGetTrackMaxSize;
    FARPROC BinkGetTrackType;
    FARPROC BinkGoto;
    FARPROC BinkIsSoftwareCursor;
    FARPROC BinkLoadSubtitles;
    FARPROC BinkLogoAddress;
    FARPROC BinkNextFrame;
    FARPROC BinkOpen;
    FARPROC BinkOpenDirectSound;
    FARPROC BinkOpenMiles;
    FARPROC BinkOpenTrack;
    FARPROC BinkOpenWaveOut;
    FARPROC BinkOpenWithOptions;
    FARPROC BinkOpenXAudio27;
    FARPROC BinkOpenXAudio28;
    FARPROC BinkOpenXAudio29;
    FARPROC BinkOpenXAudio2;
    FARPROC BinkOpenXAudio2_8;
    FARPROC BinkPause;
    FARPROC BinkRegisterFrameBuffers;
    FARPROC BinkRegisterGPUDataBuffers;
    FARPROC BinkRequestStopAsyncThread;
    FARPROC BinkRequestStopAsyncThreadsMulti;
    FARPROC BinkRestoreCursor;
    FARPROC BinkService;
    FARPROC BinkServiceSound;
    FARPROC BinkSetError;
    FARPROC BinkSetFileOffset;
    FARPROC BinkSetFrameRate;
    FARPROC BinkSetIO;
    FARPROC BinkSetIOSize;
    FARPROC BinkSetIOSize8;
    FARPROC BinkSetMemory;
    FARPROC BinkSetMixBinVolumes;
    FARPROC BinkSetMixBins;
    FARPROC BinkSetOSFileCallbacks;
    FARPROC BinkSetPan;
    FARPROC BinkSetSimulate;
    FARPROC BinkSetSoundOnOff;
    FARPROC BinkSetSoundSystem2;
    FARPROC BinkSetSoundSystem;
    FARPROC BinkSetSoundTrack;
    FARPROC BinkSetSpeakerVolumes;
    FARPROC BinkSetVideoOnOff;
    FARPROC BinkSetVolume;
    FARPROC BinkSetWillLoop;
    FARPROC BinkShouldSkip;
    FARPROC BinkStartAsyncThread;
    FARPROC BinkUseTelemetry;
    FARPROC BinkUseTmLite;
    FARPROC BinkUtilCPUs;
    FARPROC BinkUtilFree;
    FARPROC BinkUtilMalloc;
    FARPROC BinkUtilMutexCreate;
    FARPROC BinkUtilMutexDestroy;
    FARPROC BinkUtilMutexLock;
    FARPROC BinkUtilMutexLockTimeOut;
    FARPROC BinkUtilMutexUnlock;
    FARPROC BinkUtilSoundGlobalLock;
    FARPROC BinkUtilSoundGlobalUnlock;
    FARPROC BinkWait;
    FARPROC BinkWaitStopAsyncThread;
    FARPROC BinkWaitStopAsyncThreadsMulti;
    FARPROC RADSetMemory;
    FARPROC RADTimerRead;
    FARPROC YUV_blit_16a1bpp40;
    FARPROC YUV_blit_16a1bpp52;
    FARPROC YUV_blit_16a1bpp_mask48;
    FARPROC YUV_blit_16a1bpp_mask60;
    FARPROC YUV_blit_16a4bpp40;
    FARPROC YUV_blit_16a4bpp52;
    FARPROC YUV_blit_16a4bpp_mask48;
    FARPROC YUV_blit_16a4bpp_mask60;
    FARPROC YUV_blit_16bpp40;
    FARPROC YUV_blit_16bpp48;
    FARPROC YUV_blit_16bpp52;
    FARPROC YUV_blit_16bpp_mask48;
    FARPROC YUV_blit_16bpp_mask56;
    FARPROC YUV_blit_16bpp_mask60;
    FARPROC YUV_blit_24bpp40;
    FARPROC YUV_blit_24bpp48;
    FARPROC YUV_blit_24bpp52;
    FARPROC YUV_blit_24bpp_mask48;
    FARPROC YUV_blit_24bpp_mask56;
    FARPROC YUV_blit_24bpp_mask60;
    FARPROC YUV_blit_24rbpp40;
    FARPROC YUV_blit_24rbpp48;
    FARPROC YUV_blit_24rbpp52;
    FARPROC YUV_blit_24rbpp_mask48;
    FARPROC YUV_blit_24rbpp_mask56;
    FARPROC YUV_blit_24rbpp_mask60;
    FARPROC YUV_blit_32abpp40;
    FARPROC YUV_blit_32abpp52;
    FARPROC YUV_blit_32abpp_mask48;
    FARPROC YUV_blit_32abpp_mask60;
    FARPROC YUV_blit_32bpp40;
    FARPROC YUV_blit_32bpp48;
    FARPROC YUV_blit_32bpp52;
    FARPROC YUV_blit_32bpp_mask48;
    FARPROC YUV_blit_32bpp_mask56;
    FARPROC YUV_blit_32bpp_mask60;
    FARPROC YUV_blit_32rabpp40;
    FARPROC YUV_blit_32rabpp52;
    FARPROC YUV_blit_32rabpp_mask48;
    FARPROC YUV_blit_32rabpp_mask60;
    FARPROC YUV_blit_32rbpp40;
    FARPROC YUV_blit_32rbpp48;
    FARPROC YUV_blit_32rbpp52;
    FARPROC YUV_blit_32rbpp_mask48;
    FARPROC YUV_blit_32rbpp_mask56;
    FARPROC YUV_blit_32rbpp_mask60;
    FARPROC YUV_blit_UYVY40;
    FARPROC YUV_blit_UYVY48;
    FARPROC YUV_blit_UYVY52;
    FARPROC YUV_blit_UYVY_mask48;
    FARPROC YUV_blit_UYVY_mask56;
    FARPROC YUV_blit_UYVY_mask60;
    FARPROC YUV_blit_YUY240;
    FARPROC YUV_blit_YUY248;
    FARPROC YUV_blit_YUY252;
    FARPROC YUV_blit_YUY2_mask48;
    FARPROC YUV_blit_YUY2_mask56;
    FARPROC YUV_blit_YUY2_mask60;
    FARPROC YUV_blit_YV1244;
    FARPROC YUV_blit_YV1252;
    FARPROC YUV_blit_YV1256;
    FARPROC YUV_init4;
    FARPROC radfree;
    FARPROC radmalloc;

    void LoadOriginalLibrary(HMODULE module, bool bIsMemory)
    {
        dll = module;

        BinkAllocateFrameBuffers = GetProcAddress(dll, "_BinkAllocateFrameBuffers@12");
        BinkBufferBlit = GetProcAddress(dll, "_BinkBufferBlit@12");
        BinkBufferCheckWinPos = GetProcAddress(dll, "_BinkBufferCheckWinPos@12");
        BinkBufferClear = GetProcAddress(dll, "_BinkBufferClear@8");
        BinkBufferClose = GetProcAddress(dll, "_BinkBufferClose@4");
        BinkBufferGetDescription = GetProcAddress(dll, "_BinkBufferGetDescription@4");
        BinkBufferGetError = GetProcAddress(dll, "_BinkBufferGetError@0");
        BinkBufferLock = GetProcAddress(dll, "_BinkBufferLock@4");
        BinkBufferOpen = GetProcAddress(dll, "_BinkBufferOpen@16");
        BinkBufferSetDirectDraw = GetProcAddress(dll, "_BinkBufferSetDirectDraw@8");
        BinkBufferSetHWND = GetProcAddress(dll, "_BinkBufferSetHWND@8");
        BinkBufferSetOffset = GetProcAddress(dll, "_BinkBufferSetOffset@12");
        BinkBufferSetResolution = GetProcAddress(dll, "_BinkBufferSetResolution@12");
        BinkBufferSetScale = GetProcAddress(dll, "_BinkBufferSetScale@12");
        BinkBufferUnlock = GetProcAddress(dll, "_BinkBufferUnlock@4");
        BinkCheckCursor = GetProcAddress(dll, "_BinkCheckCursor@20");
        BinkClose = GetProcAddress(dll, "_BinkClose@4");
        BinkCloseTrack = GetProcAddress(dll, "_BinkCloseTrack@4");
        BinkControlBackgroundIO = GetProcAddress(dll, "_BinkControlBackgroundIO@8");
        BinkControlPlatformFeatures = GetProcAddress(dll, "_BinkControlPlatformFeatures@8");
        BinkCopyToBuffer = GetProcAddress(dll, "_BinkCopyToBuffer@28");
        BinkCopyToBufferRect = GetProcAddress(dll, "_BinkCopyToBufferRect@44");
        BinkCurrentSubtitle = GetProcAddress(dll, "_BinkCurrentSubtitle@16");
        BinkDDSurfaceType = GetProcAddress(dll, "_BinkDDSurfaceType@4");
        BinkDX8SurfaceType = GetProcAddress(dll, "_BinkDX8SurfaceType@4");
        BinkDX9SurfaceType = GetProcAddress(dll, "_BinkDX9SurfaceType@4");
        BinkDoFrame = GetProcAddress(dll, "_BinkDoFrame@4");
        BinkDoFrameAsync = GetProcAddress(dll, "_BinkDoFrameAsync@12");
        BinkDoFrameAsyncMulti = GetProcAddress(dll, "_BinkDoFrameAsyncMulti@12");
        BinkDoFrameAsyncWait = GetProcAddress(dll, "_BinkDoFrameAsyncWait@8");
        BinkDoFramePlane = GetProcAddress(dll, "_BinkDoFramePlane@8");
        BinkFindXAudio2WinDevice = GetProcAddress(dll, "_BinkFindXAudio2WinDevice@8");
        BinkFreeGlobals = GetProcAddress(dll, "_BinkFreeGlobals@0");
        BinkGetError = GetProcAddress(dll, "_BinkGetError@0");
        BinkGetFrameBuffersInfo = GetProcAddress(dll, "_BinkGetFrameBuffersInfo@8");
        BinkGetGPUDataBuffersInfo = GetProcAddress(dll, "_BinkGetGPUDataBuffersInfo@8");
        BinkGetKeyFrame = GetProcAddress(dll, "_BinkGetKeyFrame@12");
        BinkGetPalette = GetProcAddress(dll, "_BinkGetPalette@4");
        BinkGetPlatformInfo = GetProcAddress(dll, "_BinkGetPlatformInfo@8");
        BinkGetRealtime = GetProcAddress(dll, "_BinkGetRealtime@12");
        BinkGetRects = GetProcAddress(dll, "_BinkGetRects@8");
        BinkGetRects4 = GetProcAddress(dll, "_BinkGetRects@4");
        BinkGetSubtitleByIndex = GetProcAddress(dll, "_BinkGetSubtitleByIndex@16");
        BinkGetSummary = GetProcAddress(dll, "_BinkGetSummary@8");
        BinkGetTrackData = GetProcAddress(dll, "_BinkGetTrackData@8");
        BinkGetTrackData12 = GetProcAddress(dll, "_BinkGetTrackData@12");
        BinkGetTrackID = GetProcAddress(dll, "_BinkGetTrackID@8");
        BinkGetTrackMaxSize = GetProcAddress(dll, "_BinkGetTrackMaxSize@8");
        BinkGetTrackType = GetProcAddress(dll, "_BinkGetTrackType@8");
        BinkGoto = GetProcAddress(dll, "_BinkGoto@12");
        BinkIsSoftwareCursor = GetProcAddress(dll, "_BinkIsSoftwareCursor@8");
        BinkLoadSubtitles = GetProcAddress(dll, "_BinkLoadSubtitles@8");
        BinkLogoAddress = GetProcAddress(dll, "_BinkLogoAddress@0");
        BinkNextFrame = GetProcAddress(dll, "_BinkNextFrame@4");
        BinkOpen = GetProcAddress(dll, "_BinkOpen@8");
        BinkOpenDirectSound = GetProcAddress(dll, "_BinkOpenDirectSound@4");
        BinkOpenMiles = GetProcAddress(dll, "_BinkOpenMiles@4");
        BinkOpenTrack = GetProcAddress(dll, "_BinkOpenTrack@8");
        BinkOpenWaveOut = GetProcAddress(dll, "_BinkOpenWaveOut@4");
        BinkOpenWithOptions = GetProcAddress(dll, "_BinkOpenWithOptions@12");
        BinkOpenXAudio2 = GetProcAddress(dll, "_BinkOpenXAudio2@4");
        BinkOpenXAudio2_8 = GetProcAddress(dll, "_BinkOpenXAudio2@8");
        BinkOpenXAudio27 = GetProcAddress(dll, "_BinkOpenXAudio27@8");
        BinkOpenXAudio28 = GetProcAddress(dll, "_BinkOpenXAudio28@8");
        BinkOpenXAudio29 = GetProcAddress(dll, "_BinkOpenXAudio29@8");
        BinkPause = GetProcAddress(dll, "_BinkPause@8");
        BinkRegisterFrameBuffers = GetProcAddress(dll, "_BinkRegisterFrameBuffers@8");
        BinkRegisterGPUDataBuffers = GetProcAddress(dll, "_BinkRegisterGPUDataBuffers@8");
        BinkRequestStopAsyncThread = GetProcAddress(dll, "_BinkRequestStopAsyncThread@4");
        BinkRequestStopAsyncThreadsMulti = GetProcAddress(dll, "_BinkRequestStopAsyncThreadsMulti@8");
        BinkRestoreCursor = GetProcAddress(dll, "_BinkRestoreCursor@4");
        BinkService = GetProcAddress(dll, "_BinkService@4");
        BinkServiceSound = GetProcAddress(dll, "_BinkServiceSound@0");
        BinkSetError = GetProcAddress(dll, "_BinkSetError@4");
        BinkSetFileOffset = GetProcAddress(dll, "_BinkSetFileOffset@8");
        BinkSetFrameRate = GetProcAddress(dll, "_BinkSetFrameRate@8");
        BinkSetIO = GetProcAddress(dll, "_BinkSetIO@4");
        BinkSetIOSize = GetProcAddress(dll, "_BinkSetIOSize@4");
        BinkSetIOSize8 = GetProcAddress(dll, "_BinkSetIOSize@8");
        BinkSetMemory = GetProcAddress(dll, "_BinkSetMemory@8");
        BinkSetMixBinVolumes = GetProcAddress(dll, "_BinkSetMixBinVolumes@20");
        BinkSetMixBins = GetProcAddress(dll, "_BinkSetMixBins@16");
        BinkSetOSFileCallbacks = GetProcAddress(dll, "_BinkSetOSFileCallbacks@16");
        BinkSetPan = GetProcAddress(dll, "_BinkSetPan@12");
        BinkSetSimulate = GetProcAddress(dll, "_BinkSetSimulate@4");
        BinkSetSoundOnOff = GetProcAddress(dll, "_BinkSetSoundOnOff@8");
        BinkSetSoundSystem = GetProcAddress(dll, "_BinkSetSoundSystem@8");
        BinkSetSoundSystem2 = GetProcAddress(dll, "_BinkSetSoundSystem2@12");
        BinkSetSoundTrack = GetProcAddress(dll, "_BinkSetSoundTrack@8");
        BinkSetSpeakerVolumes = GetProcAddress(dll, "_BinkSetSpeakerVolumes@20");
        BinkSetVideoOnOff = GetProcAddress(dll, "_BinkSetVideoOnOff@8");
        BinkSetVolume = GetProcAddress(dll, "_BinkSetVolume@12");
        BinkSetWillLoop = GetProcAddress(dll, "_BinkSetWillLoop@8");
        BinkShouldSkip = GetProcAddress(dll, "_BinkShouldSkip@4");
        BinkStartAsyncThread = GetProcAddress(dll, "_BinkStartAsyncThread@8");
        BinkUseTelemetry = GetProcAddress(dll, "_BinkUseTelemetry@4");
        BinkUseTmLite = GetProcAddress(dll, "_BinkUseTmLite@4");
        BinkUtilCPUs = GetProcAddress(dll, "_BinkUtilCPUs@0");
        BinkUtilFree = GetProcAddress(dll, "_BinkUtilFree@4");
        BinkUtilMalloc = GetProcAddress(dll, "_BinkUtilMalloc@8");
        BinkUtilMutexCreate = GetProcAddress(dll, "_BinkUtilMutexCreate@8");
        BinkUtilMutexDestroy = GetProcAddress(dll, "_BinkUtilMutexDestroy@4");
        BinkUtilMutexLock = GetProcAddress(dll, "_BinkUtilMutexLock@4");
        BinkUtilMutexLockTimeOut = GetProcAddress(dll, "_BinkUtilMutexLockTimeOut@8");
        BinkUtilMutexUnlock = GetProcAddress(dll, "_BinkUtilMutexUnlock@4");
        BinkUtilSoundGlobalLock = GetProcAddress(dll, "_BinkUtilSoundGlobalLock@0");
        BinkUtilSoundGlobalUnlock = GetProcAddress(dll, "_BinkUtilSoundGlobalUnlock@0");
        BinkWait = GetProcAddress(dll, "_BinkWait@4");
        BinkWaitStopAsyncThread = GetProcAddress(dll, "_BinkWaitStopAsyncThread@4");
        BinkWaitStopAsyncThreadsMulti = GetProcAddress(dll, "_BinkWaitStopAsyncThreadsMulti@8");
        RADSetMemory = GetProcAddress(dll, "_RADSetMemory@8");
        RADTimerRead = GetProcAddress(dll, "_RADTimerRead@0");
        YUV_blit_16a1bpp40 = GetProcAddress(dll, "_YUV_blit_16a1bpp@40");
        YUV_blit_16a1bpp52 = GetProcAddress(dll, "_YUV_blit_16a1bpp@52");
        YUV_blit_16a1bpp_mask48 = GetProcAddress(dll, "_YUV_blit_16a1bpp_mask@48");
        YUV_blit_16a1bpp_mask60 = GetProcAddress(dll, "_YUV_blit_16a1bpp_mask@60");
        YUV_blit_16a4bpp40 = GetProcAddress(dll, "_YUV_blit_16a4bpp@40");
        YUV_blit_16a4bpp52 = GetProcAddress(dll, "_YUV_blit_16a4bpp@52");
        YUV_blit_16a4bpp_mask48 = GetProcAddress(dll, "_YUV_blit_16a4bpp_mask@48");
        YUV_blit_16a4bpp_mask60 = GetProcAddress(dll, "_YUV_blit_16a4bpp_mask@60");
        YUV_blit_16bpp40 = GetProcAddress(dll, "_YUV_blit_16bpp@40");
        YUV_blit_16bpp48 = GetProcAddress(dll, "_YUV_blit_16bpp@48");
        YUV_blit_16bpp52 = GetProcAddress(dll, "_YUV_blit_16bpp@52");
        YUV_blit_16bpp_mask48 = GetProcAddress(dll, "_YUV_blit_16bpp_mask@48");
        YUV_blit_16bpp_mask56 = GetProcAddress(dll, "_YUV_blit_16bpp_mask@56");
        YUV_blit_16bpp_mask60 = GetProcAddress(dll, "_YUV_blit_16bpp_mask@60");
        YUV_blit_24bpp40 = GetProcAddress(dll, "_YUV_blit_24bpp@40");
        YUV_blit_24bpp48 = GetProcAddress(dll, "_YUV_blit_24bpp@48");
        YUV_blit_24bpp52 = GetProcAddress(dll, "_YUV_blit_24bpp@52");
        YUV_blit_24bpp_mask48 = GetProcAddress(dll, "_YUV_blit_24bpp_mask@48");
        YUV_blit_24bpp_mask56 = GetProcAddress(dll, "_YUV_blit_24bpp_mask@56");
        YUV_blit_24bpp_mask60 = GetProcAddress(dll, "_YUV_blit_24bpp_mask@60");
        YUV_blit_24rbpp40 = GetProcAddress(dll, "_YUV_blit_24rbpp@40");
        YUV_blit_24rbpp48 = GetProcAddress(dll, "_YUV_blit_24rbpp@48");
        YUV_blit_24rbpp52 = GetProcAddress(dll, "_YUV_blit_24rbpp@52");
        YUV_blit_24rbpp_mask48 = GetProcAddress(dll, "_YUV_blit_24rbpp_mask@48");
        YUV_blit_24rbpp_mask56 = GetProcAddress(dll, "_YUV_blit_24rbpp_mask@56");
        YUV_blit_24rbpp_mask60 = GetProcAddress(dll, "_YUV_blit_24rbpp_mask@60");
        YUV_blit_32abpp40 = GetProcAddress(dll, "_YUV_blit_32abpp@40");
        YUV_blit_32abpp52 = GetProcAddress(dll, "_YUV_blit_32abpp@52");
        YUV_blit_32abpp_mask48 = GetProcAddress(dll, "_YUV_blit_32abpp_mask@48");
        YUV_blit_32abpp_mask60 = GetProcAddress(dll, "_YUV_blit_32abpp_mask@60");
        YUV_blit_32bpp40 = GetProcAddress(dll, "_YUV_blit_32bpp@40");
        YUV_blit_32bpp48 = GetProcAddress(dll, "_YUV_blit_32bpp@48");
        YUV_blit_32bpp52 = GetProcAddress(dll, "_YUV_blit_32bpp@52");
        YUV_blit_32bpp_mask48 = GetProcAddress(dll, "_YUV_blit_32bpp_mask@48");
        YUV_blit_32bpp_mask56 = GetProcAddress(dll, "_YUV_blit_32bpp_mask@56");
        YUV_blit_32bpp_mask60 = GetProcAddress(dll, "_YUV_blit_32bpp_mask@60");
        YUV_blit_32rabpp40 = GetProcAddress(dll, "_YUV_blit_32rabpp@40");
        YUV_blit_32rabpp52 = GetProcAddress(dll, "_YUV_blit_32rabpp@52");
        YUV_blit_32rabpp_mask48 = GetProcAddress(dll, "_YUV_blit_32rabpp_mask@48");
        YUV_blit_32rabpp_mask60 = GetProcAddress(dll, "_YUV_blit_32rabpp_mask@60");
        YUV_blit_32rbpp40 = GetProcAddress(dll, "_YUV_blit_32rbpp@40");
        YUV_blit_32rbpp48 = GetProcAddress(dll, "_YUV_blit_32rbpp@48");
        YUV_blit_32rbpp52 = GetProcAddress(dll, "_YUV_blit_32rbpp@52");
        YUV_blit_32rbpp_mask48 = GetProcAddress(dll, "_YUV_blit_32rbpp_mask@48");
        YUV_blit_32rbpp_mask56 = GetProcAddress(dll, "_YUV_blit_32rbpp_mask@56");
        YUV_blit_32rbpp_mask60 = GetProcAddress(dll, "_YUV_blit_32rbpp_mask@60");
        YUV_blit_UYVY40 = GetProcAddress(dll, "_YUV_blit_UYVY@40");
        YUV_blit_UYVY48 = GetProcAddress(dll, "_YUV_blit_UYVY@48");
        YUV_blit_UYVY52 = GetProcAddress(dll, "_YUV_blit_UYVY@52");
        YUV_blit_UYVY_mask48 = GetProcAddress(dll, "_YUV_blit_UYVY_mask@48");
        YUV_blit_UYVY_mask56 = GetProcAddress(dll, "_YUV_blit_UYVY_mask@56");
        YUV_blit_UYVY_mask60 = GetProcAddress(dll, "_YUV_blit_UYVY_mask@60");
        YUV_blit_YUY240 = GetProcAddress(dll, "_YUV_blit_YUY2@40");
        YUV_blit_YUY248 = GetProcAddress(dll, "_YUV_blit_YUY2@48");
        YUV_blit_YUY252 = GetProcAddress(dll, "_YUV_blit_YUY2@52");
        YUV_blit_YUY2_mask48 = GetProcAddress(dll, "_YUV_blit_YUY2_mask@48");
        YUV_blit_YUY2_mask56 = GetProcAddress(dll, "_YUV_blit_YUY2_mask@56");
        YUV_blit_YUY2_mask60 = GetProcAddress(dll, "_YUV_blit_YUY2_mask@60");
        YUV_blit_YV1244 = GetProcAddress(dll, "_YUV_blit_YV12@44");
        YUV_blit_YV1252 = GetProcAddress(dll, "_YUV_blit_YV12@52");
        YUV_blit_YV1256 = GetProcAddress(dll, "_YUV_blit_YV12@56");
        YUV_init4 = GetProcAddress(dll, "_YUV_init@4");
        radfree = GetProcAddress(dll, "_radfree@4");
        radmalloc = GetProcAddress(dll, "_radmalloc@4");
    }
} binkw32;
