#pragma once

#include <stdint.h>


struct levels_t
{
	enum
	{
		ABANDONED_CAVERN,
		ALTAR_OF_AGES,
		ALTAR_OF_HUITACA,
		ANCIENT_EL_DORADO,
		APU_ILLAPU_SHRINE,
		BATTERED_BRIDGE,
		BETA_VOLCANO,
		BITTENBINDER_CAMP,
		BUTTERFLY_GLADE,
		CAVERN_LAKE,
		CHAMELEON_TEMPLE,
		COPACANTI_LAKE,
		CRASH_SITE,
		CRYSTAL_CAVERN,
		EKKEKO_ICE_CAVERN,
		EYES_OF_DOOM,
		FIREBOMBED_TOWERS,
		FLOODED_CAVE,
		FLOODED_COURTYARD,
		GATES_OF_EL_DORADO,
		GREAT_TREE,
		JUNGLE_CANYON,
		JUNGLE_TRAIL,
		KABOOM,
		LADDER_OF_MILES,
		MAMA_OULLO_TOWER,
		MONKEY_SPIRIT,
		MONKEY_TEMPLE,
		MOUNTAIN_OVERLOOK,
		MOUNTAIN_SLED_RUN,
		MOUTH_OF_INTI,
		MYSTERIOUS_TEMPLE,
		NATIVE_JUNGLE,
		NATIVE_VILLAGE,
		PENGUIN_DEN,
		PENGUIN_SPIRIT,
		PENGUIN_TEMPLE,
		PICKAXE_RACE,
		PLANE_COCKPIT,
		PLANE_CUTSCENE,
		PUNCHAU_SHRINE,
		RAFT_BOWLING,
		RENEGADE_FORT,
		RENEGADE_HEADQUARTERS,
		RUINS_OF_EL_DORADO,
		SCORPION_SPIRIT,
		SCORPION_TEMPLE,
		SPINJA_LAIR,
		STATUES_OF_AYAR,
		ST_CLAIRE_EXCAVATION_CAMP_DAY,
		ST_CLAIRE_EXCAVATION_CAMP_NIGHT,
		TELEPORT,
		TUCO_SHOOT,
		TURTLE_MONUMENT,
		TWIN_OUTPOSTS,
		TWIN_OUTPOSTS_UNDERWATER,
		UNDERGROUND_DAM,
		VALLEY_OF_SPIRITS,
		VIRACOCHA_MONOLITHS,
		VIRACOCHA_MONOLITHS_CUTSCENE,
		WHACK_A_TUCO,
		WHITE_VALLEY,

		NUM_LEVELS
	};
};

struct level_info_t
{
	uint32_t crc;
	const char* assetName;
	const char* displayName;
};

struct level_collection_t
{
	const level_info_t* levels;
	int count;
};


extern level_collection_t levels_game;
extern level_collection_t levels_beta;


uint32_t level_get_crc( uint32_t id );
const char* level_get_name( uint32_t id );
uint32_t level_get_by_crc( uint32_t crc );

const level_info_t* level_get_info( uint32_t id );


#include "utils/func.h"

GET_FUNC( 0x6F8EC0, uint32_t, level_HashString, char* );
