# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Build mods
on:
  workflow_dispatch: #  Allows manual builds for non-master branches
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build-mods.yml"
      - "Mods/PTLE_Mods/**"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/build-mods.yml"
      - "Mods/PTLE_Mods/**"

jobs:
  Build:
    runs-on: windows-2022 # Oldest Windows still supported by GitHub
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - run: msbuild Mods/PTLE_mods/PTLE_Mods.sln /property:Configuration=Release

      - name: Create distribution folder
        run: |
          New-Item -ItemType Directory dist/mods
          Get-Item Mods/PTLE_Mods/bin/Release/*.asi | Copy-Item -Destination "dist/mods/$($_.Name)"
          Get-Item Mods/PTLE_Mods/patch/* | Copy-Item -Destination "dist/$($_.Name)"
          Copy-Item Mods/PTLE_Mods/bin/Release/binkw32.dll dist/binkw32.dll
          Copy-Item Mods/PTLE_Mods/bin/Release/config/ dist/ -Recurse
        shell: pwsh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PTLE_Mods
          path: dist
          if-no-files-found: error
